### ISSUE TITLE
Issues in the Application Form [Apply for Grant-In-Aid 2018-2019]

### ISSUE THREAD

**Issue by mubassirhayat** [codeforpakistan/kp18-hajj-aukaf-minorities-affairs#38]
Form General Info:
Apply for Grant-In-Aid 2018-2019

- [x] instead of 3 addresses we have to use one address, "Current address"
- [x] In District dropdown shows "undefined" text
- [x] address validation

**Comment by aliirz** [comment]
Allow 500 char limit for address field
