### ISSUE TITLE
Application form issues [Education section]

### ISSUE THREAD

**Issue by mubassirhayat** [codeforpakistan/kp18-hajj-aukaf-minorities-affairs#42]
@sohail0867 can you please confirm these issues and add details. 

- [x] GPA issue

**Comment by sohail0867** [comment]
In education grant gpa input gives error if I enter single digits i.e 3.4 instead of 3.40

**Comment by sohail0867** [comment]
For the grant, my suggestion would be if we can add grant information, eligibility criteria, last date for every grant so that user can see these information before applying for a grant

**Comment by Izazkhan** [comment]
This is not bug this is the default behavior of input-mask, you have to put 3.40 otherwise It won't accept, I tried to put the 0 at the end by default, but having some difficulties with that, So I left this for now!

**Comment by aliirz** [comment]
dont close issues if they are left behind.
